config/routes.rb
Rails.application.routes.draw do

  get 'healthcare_savings', to: 'pages#healthcare-savings'
  get 'instant_pay', to: 'pages#instant-pay'  
  get 'home', to: 'pages#home'
  get 'docs', to: 'pages#docs'
  get 'marketing', to: 'pages#marketing'
  get 'references', to: 'pages#references'
  get 'articles', to: 'pages#articles'
  get 'training', to: 'pages#training'
  get 'answers', to: 'pages#answers'
  get 'email-sequences', to: 'pages#email-sequences'
  get 'cold-phone-script', to: 'pages#cold-phone-script'
  get 'invite-webinar', to: 'pages#invite-webinar'
  get 'steps-to-sale', to: 'pages#steps-to-sale'
  get 'training-vids', to: 'pages#training-vids'
  get 'lead-generation', to: 'pages#lead-generation'
  get 'lead-generation-faq', to: 'pages#lead-generation-faq'
  get 'intelatek', to: 'prospects#intelatek'
  get 'dashboard', to: 'prospects#dashboard'
  get :new_lead, to: 'prospects#new_lead', as: :new_lead
  post :new_lead, to: 'prospects#new_lead_create', as: :new_lead_create
  get 'lead/:id', to: 'prospects#lead', as: :lead
  post 'lead/:id', to: 'prospects#lead_update', as: :lead_update
  get 'hcsq/:id', to: 'prospects#hcsq', as: :hcsq
  post 'hcsq/:id', to: 'prospects#hcsq_update', as: :hcsq_update
  get 'hcs/:id', to: 'prospects#hcs', as: :hcs
  post 'hcs/:id', to: 'prospects#hcs_update', as: :hcs_update  
  get 'entrust', to: 'prospects#entrust'
  get 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status', as: :hcs_lead_status
  post 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status_update', as: :hcs_lead_status_update
  get 'vcp/:id', to: 'prospects#vcp', as: :vcp
  post 'vcp/:id', to: 'prospects#vcp_update', as: :vcp_update
  get 'branch', to: 'prospects#branch'
  get 'pay/:id', to: 'prospects#pay', as: :pay
  post 'pay/:id', to: 'prospects#pay_update', as: :pay_update
  get 'shipping_profile/:id', to: 'prospects#shipping_profile', as: :shipping_profile
  post 'shipping_profile/:id', to: 'prospects#shipping_profile_update', as: :shipping_profile_update
  get 'shipping/:id', to: 'prospects#shipping', as: :shipping
  post 'shipping/:id', to: 'prospects#shipping_update', as: :shipping_update
  get 'shipstore', to: 'prospects#shipstore'
  get 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status', as: :shipping_lead_status
  post 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status_update', as: :shipping_lead_status_update
  get 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status', as: :shipping_opportunity_status
  post 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status_update', as: :shipping_opportunity_status_update  
  get :export_users, to: 'users#export_users', as: :export_users
  
  match '/users',     to: 'users#index',  via: 'get'
  
  # ************** I removed the line below to get Add User to work but not sure what effect it may have down the road ***********
  # match '/users/:id', to: 'users#show',   via: 'get'

  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'

  resources :users do
    resources :comments
    resources :attachments    
    collection { post :import }
  end

  resources :prospects do
    resources :comments
    resources :attachments    
    collection { post :import }
  end
    root 'pages#home'
  # root 'users#start_page'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prospect
  belongs_to :user
  
  def content_field
    content_fields = ['vcp_content', 'hcs_content', 'pay_content', 'shipping_content']
    content_fields.select{ |field| attributes[field].present? }.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_prospect, only: [:create, :edit, :update, :destroy]
	before_action :find_comment, only: [:edit, :update, :destroy]
  
	def create
		# creates a comment with respect to the prospect
		@comment = @prospect.comments.create(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
		  NotificationMailer.new_comment(@comment).deliver_later
			redirect_to prospect_path(@prospect)
		else
			redirect_to :back
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to prospect_path(@prospect)
		else
			redirect_to :back
		end
	end

	def destroy
		@comment.destroy
		redirect_to prospect_path(@prospect)
	end

	private

		def comment_params
			params.require(:comment).permit(:vcp_content, :hcs_content, :pay_content, :shipping_content)
		end

		def find_prospect
			@prospect = Prospect.find(params[:prospect_id])
		end

		def find_comment
			@comment = @prospect.comments.find(params[:id])
		end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="row">
    <div class="col-md-10">
    	<em><%= comment.shipping_content %><%= comment.pay_content %><%= comment.hcs_content %><%= comment.vcp_content %></em>
    	<p class="comment-posted-by">Posted by <%= comment.user.advisor_first_name + ' ' + comment.user.advisor_last_name %> on
    	<%= comment.created_at.strftime("%m/%d/%y") %></p>
		</div>

    <div class="col-md-2">
			<% if comment.user_id == current_user.id %>
				<%= link_to "Edit", edit_prospect_comment_path(comment.prospect, comment), class: "btn btn-warning btn-xs" %> &nbsp; 
				<%= link_to "Delete", prospect_comment_path(comment.prospect, comment), method: :delete,
						data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>
			<% end %>
		</div>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@prospect, @prospect.comments.build]) do |f| %>
	<%= f.input :content, label: "Add Comment" %>
	<%= f.button :submit, :class => 'btn btn-slate pull-right' %>
<% end %>

app/views/comments/_hcs_form.html.erb
<%= simple_form_for([@prospect, @prospect.comments.build]) do |f| %>
	<%= f.input :hcs_content, label: "Add Comment for HealthCare Savings" %>
	<%= f.button :submit, :class => 'btn btn-slate pull-right btn-sm' %>
<% end %>

app/views/comments/_pay_form.html.erb
<%= simple_form_for([@prospect, @prospect.comments.build]) do |f| %>
	<%= f.input :pay_content, label: "Add Comment for Instant Pay" %>
	<%= f.button :submit, :class => 'btn btn-slate pull-right btn-sm' %>
<% end %>

app/views/comments/_shipping_form.html.erb
<%= simple_form_for([@prospect, @prospect.comments.build]) do |f| %>
	<%= f.input :shipping_content, label: "Add Comment for Shipping" %>
	<%= f.button :submit, :class => 'btn btn-slate pull-right btn-sm' %>
<% end %>

app/views/comments/_vcp_form.html.erb
<%= simple_form_for([@prospect, @prospect.comments.build]) do |f| %>
	<%= f.input :vcp_content, label: "Add Comment for Virtual cards" %>
	<%= f.button :submit, :class => 'btn btn-slate pull-right btn-sm' %>
<% end %>

app/views/comments/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="prospect-show">
		<h3>Edit Comment</h3>
		<%= simple_form_for([@prospect, @comment]) do |f| %>
			<%= f.input @comment.content_field.to_sym, label: "Comment" %>
			<%= f.button :submit, :class => 'btn btn-kontrol' %>
		<% end %>
	</div>
</div>