config/routes.rb
Rails.application.routes.draw do

  get 'healthcare_savings', to: 'pages#healthcare-savings'
  get 'instant_pay', to: 'pages#instant-pay'  
  get 'home', to: 'pages#home'
  get 'docs', to: 'pages#docs'
  get 'marketing', to: 'pages#marketing'
  get 'references', to: 'pages#references'
  get 'articles', to: 'pages#articles'
  get 'training', to: 'pages#training'
  get 'answers', to: 'pages#answers'
  get 'email-sequences', to: 'pages#email-sequences'
  get 'cold-phone-script', to: 'pages#cold-phone-script'
  get 'invite-webinar', to: 'pages#invite-webinar'
  get 'steps-to-sale', to: 'pages#steps-to-sale'
  get 'training-vids', to: 'pages#training-vids'
  get 'lead-generation', to: 'pages#lead-generation'
  get 'lead-generation-faq', to: 'pages#lead-generation-faq'
  get 'intelatek', to: 'prospects#intelatek'
  get 'dashboard', to: 'prospects#dashboard'
  get :new_lead, to: 'prospects#new_lead', as: :new_lead
  post :new_lead, to: 'prospects#new_lead_create', as: :new_lead_create
  get 'lead/:id', to: 'prospects#lead', as: :lead
  post 'lead/:id', to: 'prospects#lead_update', as: :lead_update
  get 'hcsq/:id', to: 'prospects#hcsq', as: :hcsq
  post 'hcsq/:id', to: 'prospects#hcsq_update', as: :hcsq_update
  get 'hcs/:id', to: 'prospects#hcs', as: :hcs
  post 'hcs/:id', to: 'prospects#hcs_update', as: :hcs_update  
  get 'entrust', to: 'prospects#entrust'
  get 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status', as: :hcs_lead_status
  post 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status_update', as: :hcs_lead_status_update
  get 'vcp/:id', to: 'prospects#vcp', as: :vcp
  post 'vcp/:id', to: 'prospects#vcp_update', as: :vcp_update
  get 'branch', to: 'prospects#branch'
  get 'pay/:id', to: 'prospects#pay', as: :pay
  post 'pay/:id', to: 'prospects#pay_update', as: :pay_update
  get 'shipping_profile/:id', to: 'prospects#shipping_profile', as: :shipping_profile
  post 'shipping_profile/:id', to: 'prospects#shipping_profile_update', as: :shipping_profile_update
  get 'shipping/:id', to: 'prospects#shipping', as: :shipping
  post 'shipping/:id', to: 'prospects#shipping_update', as: :shipping_update
  get 'shipstore', to: 'prospects#shipstore'
  get 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status', as: :shipping_lead_status
  post 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status_update', as: :shipping_lead_status_update
  get 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status', as: :shipping_opportunity_status
  post 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status_update', as: :shipping_opportunity_status_update  
  get :export_users, to: 'users#export_users', as: :export_users
  
  match '/users',     to: 'users#index',  via: 'get'
  
  # ************** I removed the line below to get Add User to work but not sure what effect it may have down the road ***********
  # match '/users/:id', to: 'users#show',   via: 'get'

  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'

  resources :users do
    resources :comments
    resources :attachments    
    collection { post :import }
  end

  resources :prospects do
    resources :comments
    resources :attachments    
    collection { post :import }
  end
    root 'pages#home'
  # root 'users#start_page'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :prospects, :dependent => :delete_all
  has_many :comments, :dependent => :delete_all
  has_many :attachments, :dependent => :delete_all  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
        :trackable, :validatable, :timeoutable
  mount_uploader :attachment1, AttachmentUploader
  mount_uploader :attachment2, AttachmentUploader
  mount_uploader :attachment3, AttachmentUploader
  mount_uploader :attachment4, AttachmentUploader
  mount_uploader :attachment5, AttachmentUploader
  mount_uploader :attachment6, AttachmentUploader
  mount_uploader :attachment7, AttachmentUploader
  mount_uploader :attachment8, AttachmentUploader
  mount_uploader :attachment9, AttachmentUploader
  mount_uploader :attachment10, AttachmentUploader


  # def self.to_csv
  #   CSV.generate(headers: true) do |csv|
  #     csv << ["User ID", "First Name", "Last Name", "Prospects", "Logged in", "Email", "Phone",
  #             "Mobile", "Group", "Manager", "Support"]
  #     all.each do |user|
  #       csv << [user.id, user.advisor_first_name, user.advisor_last_name, user.prospects.size, 
  #               user.current_sign_in_at, user.email, user.advisor_phone,
  #               user.advisor_mobile, user.group, user.manager, user.support]
  #     end
  #   end
  # end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end  


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # Use the following line to import just new user
      # User.create! row.to_hash
      # Or use The following 3 lines to update existing users
      user_hash = row.to_hash
      user = find_or_create_by!(id: user_hash['id'])
      user.update_attributes(user_hash)
    end
  end

    
  def self.search(query)
    # Note that PostgreSQL is case specific for like when searching where sqlite3 is not
    where("LOWER(advisor_first_name) like ? OR LOWER(advisor_last_name) like ? OR LOWER(email) like ? OR LOWER(advisor_phone) like ? OR LOWER(advisor_mobile) like ?", "%#{query.downcase}%", "%#{query.downcase}%", "%#{query.downcase}%", "%#{query.downcase}%", "%#{query.downcase}%")
  end


  def password_required?
    false
  end
  
  def advisor_name
    [advisor_first_name, advisor_last_name].select(&:present?).join(' ')
  end
  
  def self.collection
    order(:advisor_first_name).map { |u| [u.advisor_name, u.id] }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :import, :new]
  before_action :set_user, only: [:show, :edit, :destroy, :update]

  def index
    # if params[:search]
    #   @users = User.search(params[:search]).order("created_at DESC").paginate(:per_page => 5, :page => params[:page])
    # else
    #   @users = User.all.paginate(:per_page => 5, :page => params[:page])
    @state = User.select(:state).order(:state).distinct
    if params[:state] != nil
      @users = User.where(state: params[:state]).paginate(:per_page => 10, :page => params[:page])
    elsif params[:search]
      @users = User.search(params[:search]).order("created_at DESC").paginate(:per_page => 10, :page => params[:page])
    else
      @users = User.all.paginate(:per_page => 10, :page => params[:page])
      # respond_to do |format|
      #   format.html
      #   format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
      # end
    end
  end

  def export_users
      @users = User.all
      respond_to do |format|
        format.html
        format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
      end
  end

  def import
    User.import(params[:file])
    redirect_to root_url, notice: "Users imported."
  end



  def new
    @user = User.new
  end


  def create
    attrs = user_params
    @user = User.new(attrs)
    if @user.save
      flash[:success] = "New User Added."
      redirect_to users_path
    else
      render 'new'
    end
  end


  def show
  end

  # def start_page
  #   if current_user.manager
  #     @users = User.all
  #     @prospects = Prospect.all
  #     render(:template => 'prospects/dashboard')
  #   else
  #     render(:template => 'pages/home')
  #   end
  # end

  def edit
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def update
	  if @user.update_attributes(user_params)
		  redirect_to users_path
	  else
	  	render 'edit'
	  end
  end


  private

  def set_user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:advisor_first_name, :advisor_last_name, :advisor_phone, :advisor_mobile, :advisor_home_phone, :admin, :manager, :support, :staff, :email, :password, :password_confirmation, :group, :entrust, :branch, :mailing_address, :apt_suite, :city, :state, :zip, :advisor_company_name, :intelatek, :attachment1, :attachment2, :attachment3, :attachment4, :attachment5, :attachment6, :attachment7, :attachment8, :attachment9, :attachment10, :attachment1_name, :attachment2_name, :attachment3_name, :attachment4_name, :attachment5_name, :attachment6_name, :attachment7_name, :attachment8_name, :attachment9_name, :attachment10_name, :training_date, :business_plan_date, :signup_date, :fee, :occupation, :broker, :fee_payment_method, :shipstore)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if current_user.manager || current_user.staff %>
  <div class="col-md-10 col-md-offset-1">

	<div class="panel panel-gray">
	  <div class="panel-heading">
	  	
	  	<div class="row">
	  		<div class="col-md-3">
          <h4>Listing <%= User.count %> Users</h4>
	  		</div>
	  		<div class="col-md-4">
      		<%= form_tag(users_path, :method => "get", id: "search-form") do %>
      			<%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
      			<%= submit_tag "Search", class:"btn btn-slate btn-sm" %>
      		<% end %>
	  		</div>
	  		<div class="col-md-2">
	  		  <% if current_user.staff %>
            <%= link_to "Export Users", export_users_path(format: "csv"), class: "btn btn-beige btn-xs" %>
          <% end %>
	  		</div>

	  		<div class="col-md-3">
					<% if current_user.admin %>
					  <%= form_tag import_users_path, multipart: true do %>
					  <%= file_field_tag :file %><%= submit_tag "Import Users", class:"btn btn-danger btn-xs" %>
					  <% end %>
					<% end %>
	  		</div>
	  	</div>
	  	
	  </div>

  	<div class="prospect-show">
  
    	<div class="prospect-show table-responsive">
        <table class="table table-sm index-table table-condensed">
          <thead>
            <tr>
              <th colspan="3"></th>
              <% if current_user.staff %>
                <th colspan="5">Prospects</th>
                <th></th>                
                <th colspan="3">Vendor</th>
                <th colspan="4">Permissions</th>
              <% end %>
            </tr>
              <th class="th-left">Name</th>
              <th>
                <div class="status">
  				      	<li class="dropdown">
  								  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong>State </strong><span class="caret"></span></a>
  								  <ul class="dropdown-menu dropdown-menu-right status-menu" style="list-style: none;">
  								    <li><%= link_to "All", users_path %></li>
  								    <% @state.each do |h| %>
  								      <li class="black"><%= link_to "#{h.state}", users_path(state: h.state) %></li>
  								    <% end %>
  								  </ul>
  								</li>
  							</div>
  						</th>
              <% if !current_user.staff %>
                <th>Prospects</th>
              <% else %>
                <th>Last Logged In</th>              
                <th>Ship</th>
                <th>HCS</th>
                <th>Pay</th>
                <th>AP</th>
                <th>Total</th>                
                <th>Group</th>    
                <th>Shipstore</th>
                <th>Entrust</th>
                <th>Branch</th>
                <th>Admin</th>
                <th>Manager</th>
                <th>Staff</th>
              <% end %>
              <% if current_user.intelatek || current_user.admin %>
                <th>IntelaTek</th>
              <% end %>
            </tr>
          </thead>
               
          <tbody>
            <% @users.order(:advisor_first_name).each do |user| %>
              <tr>
              	<td class="td-left"><%= link_to user.advisor_name, user %></td>
              	<td style="vertical-align:middle"><%= user.state %></td>
                <% if current_user.staff %>
                	<td style="vertical-align:middle">
                	  <% if user.current_sign_in_at %>
                	    <%= time_ago_in_words(user.current_sign_in_at) if user.current_sign_in_at %> ago
                	  <% else %>
                	    Never
                	  <% end %>
                	 </td>
                <% end %>

                <% if current_user.shipstore || current_user.staff %>
                	<td style="vertical-align:middle"><%= user.prospects.where(shipping_prospect: true).count %></td>
                <% end %>
                <% if current_user.entrust || current_user.staff %>              	
                	<td style="vertical-align:middle"><%= user.prospects.where(hcs_prospect: true).count %></td>
                <% end %>
                <% if current_user.branch || current_user.staff %> 
                	<td style="vertical-align:middle"><%= user.prospects.where(pay_prospect: true).count %></td>
                <% end %>
                <% if current_user.staff %>
                	<td style="vertical-align:middle"><%= user.prospects.where(vcp_prospect: true).count %></td>              	
                	<td style="vertical-align:middle"><%= user.prospects.size %></td>
                	<td style="vertical-align:middle"><%= user.group %></td>
                	<td style="vertical-align:middle">
                	  <% if user.shipstore == true %><span class="glyphicon glyphicon-ok"></span><% end %></td>
                	<td style="vertical-align:middle">
                	  <% if user.entrust == true %><span class="glyphicon glyphicon-ok"></span><% end %></td>
                	<td style="vertical-align:middle">
                	  <% if user.branch == true %><span class="glyphicon glyphicon-ok"></span><% end %></td>
                	<td style="vertical-align:middle">
                	  <% if user.admin == true %><span class="glyphicon glyphicon-ok"></span><% end %></td>
                	<td style="vertical-align:middle">
                	  <% if user.manager == true %><span class="glyphicon glyphicon-ok"></span><% end %></td>
                	<td style="vertical-align:middle">
                	  <% if user.staff == true %><span class="glyphicon glyphicon-ok"></span><% end %></td>
                <% end %>
                <% if current_user.intelatek || current_user.admin %>
                  <td style="vertical-align:middle">
              	  <% if user.intelatek == true %><span class="glyphicon glyphicon-ok"></span><% end %></td>
                <% end %>
      		    </tr>
        		<% end %>
        		
          </tbody>
        		<tr><td colspan="15" style="text-align:middle"><%= will_paginate @users, renderer: BootstrapPagination::Rails %></td></tr>
          
        </table>

      </div>

    </div>
		<div class="panel-footer center">
		</div>        

  </div>
<% end %>

app/views/users/show.html.erb
<% if current_user.manager || current_user.staff %>
  <div class="col-md-10 col-md-offset-1">
  	<div class="panel panel-gray">
      <div class="panel-heading">
        <h4><%= @user.advisor_first_name + ' ' + @user.advisor_last_name %></h4>
      </div>
      <div class="prospect-show">
      	
        <div class="row">

          <div class="col-md-5 col-md-offset-1">
		        <table valign="middle">

		          <tr>
		            <td>Consultant: </td><td>&nbsp;&nbsp;</td><td><%= @user.advisor_first_name + ' ' + @user.advisor_last_name %></td>
		          </tr>
		          <tr>
		            <td colspan="2">&nbsp;</td>
		          </tr>	
		          <tr>
		            <td>Company: </td><td>&nbsp;&nbsp;</td><td><%= @user.advisor_company_name %></td>
		          </tr>
		          <tr>
		            <td colspan="2">&nbsp;</td>
		          </tr>			          
		          <tr>
		            <td>Phone: </td><td>&nbsp;&nbsp;</td><td><%= @user.advisor_phone %></td>
		          </tr>
		          <tr>
		            <td colspan="2">&nbsp;</td>
		          </tr>	
		          <tr>
		            <td>Mobile: </td><td>&nbsp;&nbsp;</td><td><%= @user.advisor_mobile %></td>    
		          </tr>
		          <tr>
		            <td colspan="2">&nbsp;</td>
		          </tr>	
		          <tr>
		            <td>Home Phone: </td><td>&nbsp;&nbsp;</td><td><%= @user.advisor_home_phone %></td>
		          </tr>
		          <tr>
		            <td colspan="2">&nbsp;</td>
		          </tr>			          
		          <tr>
		            <td>Email: </td><td>&nbsp;&nbsp;</td><td><%= @user.email %></td>
		          </tr>
		          <tr>
		            <td colspan="2">&nbsp;</td>
		          </tr>	
		          <tr>
		            <td>Address: &nbsp;&nbsp;<br>&nbsp;</td><td>&nbsp;&nbsp;</td><td><%= @user.mailing_address %><br>
		              <%= @user.apt_suite %>
		              <%= @user.city %>, <%= @user.state %>  <%= @user.zip %>
		          		<br>
		            </td>
		          </tr>
		          <% if current_user.staff %>
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>
			          <tr>
			            <td>Occupation: </td><td>&nbsp;&nbsp;</td><td><%= @user.occupation %></td>
			          </tr>
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>	
			          <tr>
			            <td>Sign Date: </td><td>&nbsp;&nbsp;</td><td><%= @user.signup_date %></td>
			          </tr>		  
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>	
			          <tr>
			            <td>Training Completed Date: </td><td>&nbsp;&nbsp;</td><td><% if !@user.training_date.nil? %>
			    		  																					<%= @user.training_date.strftime("%m/%d/%y") %>
			      																						<% end %></td>
			          </tr>
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>			          
			          <tr>
			            <td>Business Plan Scheduled<br>
			            		or Completed Date: </td><td>&nbsp;&nbsp;</td><td><% if !@user.business_plan_date.nil? %>
																				    		 		<%= @user.business_plan_date.strftime("%m/%d/%y") %>
																									<% end %></td>
			          </tr>
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>
          
							<% end %>
						</table>
					</div>

		      <% if current_user.staff %>
	          <div class="col-md-5 col-md-offset-1">
					
							<p><strong>Documents</strong></p>
							
							<ul>
								<%= link_to "#{@user.attachment1_name}", @user.attachment1_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment2_name}", @user.attachment2_url, target: :_blank %><br><br>  	
								<%= link_to "#{@user.attachment3_name}", @user.attachment3_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment4_name}", @user.attachment4_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment5_name}", @user.attachment5_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment6_name}", @user.attachment6_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment7_name}", @user.attachment7_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment8_name}", @user.attachment8_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment9_name}", @user.attachment9_url, target: :_blank %><br><br>
								<%= link_to "#{@user.attachment10_name}", @user.attachment10_url, target: :_blank %><br>
							</ul>
							
							<table>
			          <tr>
			            <td>Broker: </td><td>&nbsp;&nbsp;<%= @user.broker %></td>
			          </tr>        
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>			          
			          <tr>
			            <td>Fee Paid: </td><td>&nbsp;&nbsp;<%= @user.fee %></td>
			          </tr>        
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>
			          <tr>
			            <td>Fee Paid by: </td><td>&nbsp;&nbsp;<%= @user.fee_payment_method %></td>
			          </tr>
			          <tr>
			            <td colspan="2">&nbsp;</td>
			          </tr>			          							
							</table>
						</div>
					<% end %>
				</div>

		    <% if current_user.staff %>
	        <div class="row">
	          <div class="col-md-10 col-md-offset-1">
	          	<hr>
							<p><strong>Notes</strong></p>
						</div>
					</div>
				<% end %>
      </div>
      
    	<div class="panel-footer">
    		<div class="links center">
    			<%= link_to "Back", users_path, class: "btn btn-beige" %> &nbsp;&nbsp;
    			<% if current_user.staff %>
    				<%= link_to "Edit User", edit_user_path(@user), class: "btn btn-warning" %>
          	<%#= link_to "Delete User", user_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-danger" %>
          <% end %>
    		</div>
       </div>
    </div>
    <% end %>
  </div>


<% if current_user.manager %>

<div class="col-md-12">
  <p>&nbsp;</p>
	<div class="panel panel-gray">
	  <div class="panel-heading">
	  	<div class="row">
	  		<div class="col-md-6">
	  			<h4>Listing
						<% if current_user.staff %>
			 				<%= @user.prospects.count %>
						<% else %>
							All
						<% end %>
					Prospects</h4>
	  		</div>
	  		<!--<div class="col-md-6">-->
		  	<!--	<%#= form_tag(prospects_path, :method => "get", id: "search-form") do %>-->
					<!--	<%#= text_field_tag :search, params[:search], placeholder: "Search Prospects" %>-->
					<!--	<%#= submit_tag "Search", class:"btn btn-slate btn-sm" %>-->
					<!--<%# end %>-->
	  		<!--</div>-->
	  	</div>
	  </div>
		<div class="prospect-show table-responsive">
			<table class="table index-table table-condensed">
		  	<tr>
		  		<% if current_user.shipstore %>
		  		  <td colspan="4">Shipping</td>
		  		<% elsif current_user.entrust %>
		  			<td colspan="4">HealthCare Savings</td>
		  		<% elsif current_user.branch %>
		  		  <td colspan="5">Instant Pay</td>
		  	  <% end %>
		  	</tr>

		    <tr>
		      <td><strong>Prospect<br>Organization Name</strong></td>
					<% if current_user.shipstore || current_user.entrust %>
			      <td><strong>Next Action</strong></td>
  		      <td><strong>Status</strong></td>
					<% elsif current_user.branch %>
			      <td><strong>Submitted<br>to Branch</strong></td>
			      <td><strong>Next Action</strong></td>
  		      <td><strong>Status</strong></td>
          <% else %>
			      <td><strong>Shipping<br>Next Action</strong></td>			      
			      <td><strong>HealthCare<br>Next Action</strong></td>
  		      <td><strong>Instant Pay<br>Next Action</strong></td>
  		      <td><strong>Accounts Payable<br>Next Action</strong></td>    
          <% end %>          
				</tr>
				
			  <tbody class="bordered">
  		  	<% if current_user.shipstore %>
						<% @user.prospects.where(shipping_prospect: true).each do |prospect| %>
							<tr>
				      	<td class="td-left"><%= link_to prospect.organization, prospect %></td>
				      	
					      <td class="td-left">
					      	<% if !prospect.shipping_next_action_date.nil? %>
				      			<% if prospect.shipping_next_action_date < Date.today %>
				      				<div class="alert-alert">
				      			<% else %>
				      				<div>
				      			<% end %>		
				      			<%= prospect.shipping_next_action_date.strftime("%m/%d/%Y") %> - <%= prospect.shipping_next_action %>
				      			</div>
				      		<% end %>
					      </td>
					      
					      <td><%= prospect.shipping_opportunity_status %></td>
					    </tr>
			    	<% end %>
  		    <% elsif current_user.entrust %>
						<% @user.prospects.where(hcs_prospect: true).each do |prospect| %>
							<tr>
				      	<td class="td-left"><%= link_to prospect.organization, prospect %></td>
					      <td class="td-left">
					      	<% if !prospect.hcs_next_action_date.nil? %>
				      			<% if prospect.hcs_next_action_date < Date.today %>
				      				<div class="alert-alert">
				      			<% else %>
				      				<div>
				      			<% end %>		
				      			<%= prospect.hcs_next_action_date.strftime("%m/%d/%Y") %> - <%= prospect.hcs_next_action %>
				      			</div>
			      			<% end %>
					      </td>
					      <td><%= prospect.hcs_opportunity_status %></td>
					    </tr>
				   	<% end %>
  		    <% elsif current_user.branch %>
						<% @user.prospects.where(pay_prospect: true).each do |prospect| %>
							<tr>
					      <td class="td-left"><%= link_to prospect.organization, prospect %></td>  		  		    
            		<td style="vertical-align:middle">
            	  <% if prospect.pay_submitted_to_branch? %><span class="glyphicon glyphicon-ok"></span><% end %></td>
					      <td class="td-left">
					      	<% if !prospect.pay_next_action_date.nil? %>
				      			<% if prospect.pay_next_action_date < Date.today %>
				      				<div class="alert-alert">
				      			<% else %>
				      				<div>
				      			<% end %>		
				      			<%= prospect.pay_next_action_date.strftime("%m/%d/%Y") %> - <%= prospect.pay_next_action %>
				      			</div>
				      		<% end %>
					      </td>			
					      <td><%= prospect.pay_status %></td>
					    </tr>
				   	<% end %>
			   	<% else %>
						<% @user.prospects.each do |prospect| %>  
					    <tr>
					      <td class="td-left"><%= link_to prospect.organization, prospect %></td>  					   	
					   		<td class="td-left"><%= prospect.shipping_opportunity_status %><br>
										<% if !prospect.shipping_next_action_date.nil? %>
					      			<% if prospect.shipping_next_action_date < Date.today %>
					      				<div class="alert-alert">
					      			<% else %>
					      				<div>
					      			<% end %>		
					      			<%= prospect.shipping_next_action_date.strftime("%m/%d/%Y") %> - <%= prospect.shipping_next_action %>
					      			</div>
					      		<% end %>					   		
					   		</td>

					   		<td class="td-left"><%= prospect.hcs_opportunity_status %><br>
					      	<% if !prospect.hcs_next_action_date.nil? %>
				      			<% if prospect.hcs_next_action_date < Date.today %>
				      				<div class="alert-alert">
				      			<% else %>
				      				<div>
				      			<% end %>		
				      			<%= prospect.hcs_next_action_date.strftime("%m/%d/%Y") %> - <%= prospect.hcs_next_action %>
				      			</div>
			      			<% end %>					   		
					   		</td>
					   		
					   		<td class="td-left"><%= prospect.pay_status %><br>
					      	<% if !prospect.pay_next_action_date.nil? %>
				      			<% if prospect.pay_next_action_date < Date.today %>
				      				<div class="alert-alert">
				      			<% else %>
				      				<div>
				      			<% end %>		
				      			<%= prospect.pay_next_action_date.strftime("%m/%d/%Y") %> - <%= prospect.pay_next_action %>
				      			</div>
				      		<% end %>
					   		</td>
					   		<td><%= prospect.vcp_status %><br>
					      	<% if !prospect.vcp_next_action_date.nil? %>
				      			<% if prospect.vcp_next_action_date < Date.today %>
				      				<div class="alert-alert">
				      			<% else %>
				      				<div>
				      			<% end %>		
				      			<%= prospect.vcp_next_action_date.strftime("%m/%d/%Y") %> - <%= prospect.vcp_next_action %>
				      			</div>
				      		<% end %>
					   		</td>
						  </tr>
				   	<% end %>
          <% end %>
			  </tbody>

			</table>
  	</div>
  	<div class="panel-footer">
	 	</div>
  </div>
<% end %>