config/routes.rb
Rails.application.routes.draw do

  get 'healthcare_savings', to: 'pages#healthcare-savings'
  get 'instant_pay', to: 'pages#instant-pay'  
  get 'home', to: 'pages#home'
  get 'docs', to: 'pages#docs'
  get 'marketing', to: 'pages#marketing'
  get 'references', to: 'pages#references'
  get 'articles', to: 'pages#articles'
  get 'training', to: 'pages#training'
  get 'answers', to: 'pages#answers'
  get 'email-sequences', to: 'pages#email-sequences'
  get 'cold-phone-script', to: 'pages#cold-phone-script'
  get 'invite-webinar', to: 'pages#invite-webinar'
  get 'steps-to-sale', to: 'pages#steps-to-sale'
  get 'training-vids', to: 'pages#training-vids'
  get 'lead-generation', to: 'pages#lead-generation'
  get 'lead-generation-faq', to: 'pages#lead-generation-faq'
  get 'intelatek', to: 'prospects#intelatek'
  get 'dashboard', to: 'prospects#dashboard'
  get :new_lead, to: 'prospects#new_lead', as: :new_lead
  post :new_lead, to: 'prospects#new_lead_create', as: :new_lead_create
  get 'lead/:id', to: 'prospects#lead', as: :lead
  post 'lead/:id', to: 'prospects#lead_update', as: :lead_update
  get 'hcsq/:id', to: 'prospects#hcsq', as: :hcsq
  post 'hcsq/:id', to: 'prospects#hcsq_update', as: :hcsq_update
  get 'hcs/:id', to: 'prospects#hcs', as: :hcs
  post 'hcs/:id', to: 'prospects#hcs_update', as: :hcs_update  
  get 'entrust', to: 'prospects#entrust'
  get 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status', as: :hcs_lead_status
  post 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status_update', as: :hcs_lead_status_update
  get 'vcp/:id', to: 'prospects#vcp', as: :vcp
  post 'vcp/:id', to: 'prospects#vcp_update', as: :vcp_update
  get 'branch', to: 'prospects#branch'
  get 'pay/:id', to: 'prospects#pay', as: :pay
  post 'pay/:id', to: 'prospects#pay_update', as: :pay_update
  get 'shipping_profile/:id', to: 'prospects#shipping_profile', as: :shipping_profile
  post 'shipping_profile/:id', to: 'prospects#shipping_profile_update', as: :shipping_profile_update
  get 'shipping/:id', to: 'prospects#shipping', as: :shipping
  post 'shipping/:id', to: 'prospects#shipping_update', as: :shipping_update
  get 'shipstore', to: 'prospects#shipstore'
  get 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status', as: :shipping_lead_status
  post 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status_update', as: :shipping_lead_status_update
  get 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status', as: :shipping_opportunity_status
  post 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status_update', as: :shipping_opportunity_status_update  
  get :export_users, to: 'users#export_users', as: :export_users
  
  match '/users',     to: 'users#index',  via: 'get'
  
  # ************** I removed the line below to get Add User to work but not sure what effect it may have down the road ***********
  # match '/users/:id', to: 'users#show',   via: 'get'

  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'

  resources :users do
    resources :comments
    resources :attachments    
    collection { post :import }
  end

  resources :prospects do
    resources :comments
    resources :attachments    
    collection { post :import }
  end
    root 'pages#home'
  # root 'users#start_page'
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :delete_all
  has_many :attachments, :dependent => :delete_all
  validates :organization, :presence => true
  validates :user_id, :presence => true
  # validates :intro_presentation_date, :presence => true
  # validates :employees, :numericality => {:only_integer => true}
  # validates :pay_hourly_employees, :numericality => {:only_integer => true}
  delegate :email, to: :user, allow_nil: true, prefix: true

  # def self.to_csv
  #   CSV.generate(headers: true) do |csv|
  #     csv << ["advisor_name", 
  #             "email", 
  #             "advisor_phone", 
  #             "advisor_mobile", 
  #             "organization", 
  #             "street_address", 
  #             "address2", 
  #             "city", 
  #             "state", 
  #             "zip", 
  #             "phone", 
  #             "website"]
  #     all.each do |prospect|
  #       advisor_name = prospect.user.advisor_first_name + " " + prospect.user.advisor_last_name
  #       csv << [prospect.user.advisor_name, 
  #               prospect.user.email, 
  #               prospect.user.advisor_phone, 
  #               prospect.user.advisor_mobile, 
  #               prospect.organization, 
  #               prospect.street_address, 
  #               prospect.address2, 
  #               prospect.city, 
  #               prospect.state, 
  #               prospect.zip, 
  #               prospect.phone, 
  #               prospect.website]
  #     end
  #   end
  # end

  def self.to_csv_index
    CSV.generate do |csv|
      csv << column_names
      all.each do |prospect|
        csv << prospect.attributes.values_at(*column_names)
      end
    end
  end

  def self.to_csv_shipping_store
    prospects = self.where(shipping_prospect: true).order("created_at DESC")

    CSV.generate do |csv|
      attributes = %w[Organization Adress City State ZIP Phone Contact_First_name Contact_Last_Name Contact_Title Contact_Phone Contact_Mobile Contact_Email Shipping_Status]
      csv << attributes
      prospects.each do |prospect|
        row = []
        row << prospect.organization
        row << prospect.street_address
        row << prospect.city
        row << prospect.state
        row << prospect.zip
        row << prospect.phone
        row << prospect.contact1_first_name
        row << prospect.contact1_last_name
        row << prospect.contact1_title
        row << prospect.contact1_phone
        row << prospect.contact1_mobile
        row << prospect.contact1_email
        row << prospect.shipping_opportunity_status
        csv << row
      end
    end
  end

# Built this import function with Alfie
  # def self.import(file)
  #   CSV.foreach(file.path, encoding: 'bom|utf-8', headers: true) do |row|
  #     prospect_hash = row.to_hash.select{ |k,v| v.present? }
  #     prospect = find_or_initialize_by(id: prospect_hash['id'])
  #     #binding.pry
  #     prospect.assign_attributes(prospect_hash.except('id'))
  #     prospect.save
  #     dates_hash = prospect_hash.slice('created_at', 'updated_at')
  #     dates_hash.each{|k, v| dates_hash[k] = DateTime.strptime(v, "%m/%d/%Y") }
  #     prospect.update_columns(dates_hash) if dates_hash.present?
  #   end
  # end

  # Use The following just to update existing prospects
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      prospect_hash = row.to_hash
      prospect = find_or_create_by!(id: prospect_hash['id'])
      prospect.update_attributes(prospect_hash)
    end
  end


  # Use the following line to import just new prospects
  # def self.import(file)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     Prospect.create! row.to_hash
  #   end
  # end



  def self.search(query)
    # Note that PostgreSQL is case specific for like when searching where sqlite3 is not
    where("LOWER(organization) like ?", "%#{query.downcase}%")
    # To search by more than one variable, do the following
    # where("LOWER(organization) like ? OR LOWER(status) like ?", "%#{query.downcase}%", "%#{query.downcase}%")
  end
  
end

app/helpers/prospects_helper.rb
module ProspectsHelper

  # Dashboard


  def shipping_no_sale
    @prospects.where(shipping_opportunity_status: "Closed Lost").count +
    @prospects.where(shipping_opportunity_status: "Closed Not Qualified").count +
    @prospects.where(shipping_opportunity_status: "Lead Declined by ShipStore").count
  end
  
  def hcs_no_sale
    @prospects.where(hcs_opportunity_status: "Intro Pres Given - No Sale").count +
    @prospects.where(hcs_opportunity_status: "Fact Finder Call Done - No Sale").count +
    @prospects.where(hcs_opportunity_status: "Proposal Given - No Sale").count +
    @prospects.where(hcs_opportunity_status: "Not Qualified").count +
    @prospects.where(hcs_opportunity_status: "Other - No Sale").count
  end

  def pay_no_sale
    @prospects.where(pay_status: "Intro Pres Given - No Sale").count +
    @prospects.where(pay_status: "SME Presentation Done - No Sale").count +
    @prospects.where(pay_status: "Not Qualified").count +
    @prospects.where(pay_status: "Other - No Sale").count
  end


end

app/views/prospects/_hcs_show.html.erb
    <% if @prospect.hcs_prospect  %>
      <p>&nbsp;</p>

      <div class="row">
        <div class="col-md-3">
          <h4><strong>HealthCare Savings</strong></h4>
        </div>
    
        <div class="col-md-5"><br>
          Status: <em><%= @prospect.hcs_opportunity_status %></em><br>
      		    <% if !@prospect.hcs_next_action_date.nil? %>
	      			<% if @prospect.hcs_next_action_date < Date.today %>
	      				<div class="alert-alert">
	      			<% else %>
	      				<div>
	      			<% end %>		
	      			Next Action: <em><%= @prospect.hcs_next_action_date.strftime("%m/%d/%Y") %> - <%= @prospect.hcs_next_action %></em>
	      			</div>
	      		<% end %>
        </div>
        <div class="col-md-2"><strong><br>Lead Status</strong><br><em>
          <% if @prospect.hcs_lead_status == "Submitted" %>Not Yet Reviewed
          <% elsif @prospect.hcs_lead_status == "Pending Review" %>Pending Discovery Call
          <% elsif @prospect.hcs_lead_status == "Approved" %>Accepted
          <% elsif @prospect.hcs_lead_status == "Declined" %>Declined
          <% end %></em>
        </div>        
        <div class="col-md-2"><br>
          <%= link_to "Edit HealthCare Savings", hcs_path(@prospect), class: "btn btn-warning btn-sm" %>
        </div>
      </div>
      <p>&nbsp;</p>
  
    <div class="row">
      <div class="col-md-4">
        Intro Pres Date: <% if !@prospect.intro_presentation_date.nil? %>
  		  <em><%= @prospect.intro_presentation_date.strftime("%m/%d/%Y") %></em><% end %>
  		  <br>
  		  Intro Presented by: <em><%= @prospect.intro_presenter %></em>
      </div>
      <div class="col-md-4">
        SME Presentation Date: <% if !@prospect.hcs_sme_fact_finding_call_date.nil? %>
  		  <%= @prospect.hcs_sme_fact_finding_call_date.strftime("%m/%d/%Y") %></em><% end %>
  		  <br>
  		  Subject Matter Expert: <em><%= @prospect.hcs_sme %></em><br>
  		  <br>
  		  New Cost: <% if @prospect.new_estimated_health_benefit_cost != 0 %>
  		              <em><%= number_to_currency(@prospect.new_estimated_health_benefit_cost, precision: 0) %></em>
  		            <% end %>
      </div>
      <div class="col-md-4">
        Proposal Meeting Date: <% if !@prospect.hcs_sme_proposal_meeting_date.nil? %>
  		  <em><%= @prospect.hcs_sme_proposal_meeting_date.strftime("%m/%d/%Y") %></em><% end %>
        <br>
        Agreement Date: <% if !@prospect.agreement_date.nil? %>
  			<em><%= @prospect.agreement_date.strftime("%m/%d/%Y") %></em><% end %>
  			<br>
    	  Effective Date: <% if !@prospect.effective_date.nil? %>
  			<em><%= @prospect.effective_date.strftime("%m/%d/%Y") %></em><% end %>
      </div>
    </div>

    <p>&nbsp;</p>
    
    <div class="row">
      <div class="col-md-12">
        HCS Notes: <em><%= @prospect.hcs_notes %></em>
      </div>
    </div>
  
    <p>&nbsp;</p>

    <h4>HCSQ - HealthCare Savings Questionaire</h4>
    <div class="row">
      <div class="col-md-4">
    		<p>Current Carrier: <em><%= @prospect.hcbq_current_carrier %></em></p>
    		<p>Current Coverage Type: <em><%= @prospect.hcbq_current_coverage_type %></em></p>
    		<p>Renewal Month: <em><%= @prospect.renewal_month %></em></p>
    		<p>Current Annual Cost: 
    		    <% if @prospect.current_health_benefit_cost != 0 %>
	            <em><%= number_to_currency(@prospect.current_health_benefit_cost, precision: 0) %></em>
	          <% end %>
    		    <br><em>(employer & employee contributions)</em></p>
    		<p># of Eligible Employees:  <em><%= @prospect.hcbq_no_of_eligible_employees %></em></p>
    		<p>Total Participating:  <em><%= @prospect.hcbq_total_participation %></em></p>
    		<p>Nature of Business: <em><%= @prospect.hcbq_business_type %></em></p>
        <p>&nbsp;</p>
    		<p><em><%= @prospect.hcbq_notes %></em></p>    		
      </div>
      
      <div class="col-md-8">
    		<p>1) For you & your employees, what are the 3 most important elements of your health plan?<br>
    		  <em class="tab"><%= @prospect.hcbq_most_important %></em></p>
    		  
    		<p>2) Do you think the last 3 years of compounding increases in your health benefit costs would be sustainable if continued for the next three years?<br>
    		  <em class="tab"><%= @prospect.hcbq_sustainable %></em></p>
    		  
    		<p>3) Do you think your employees can afford their deductible & out-of-pocket expense under your current plan?<br>
    		  <em class="tab"><%= @prospect.hcbq_oop %></em></p>
    		  
    		<p>4) What do you like best about your health plan?<br>
    		<em class="tab"><%= @prospect.hcbq_like_best %></em></p>
  
    		<p>5) What do you like least about your health plan?<br>
    		<em class="tab"><%= @prospect.hcbq_like_least %></em></p>
  
    		<p>6) On a scale of 1 to 10, how would you rate your current agent/broker/consultant?<br>
    		  <em class="tab"><%= @prospect.hcbq_scale %></em></p>
  
    		<p>7) If you could design the perfect benefit plan for your company what would it look like?<br>
    		  <em class="tab"><%= @prospect.hcbq_perfect_plan %></em></p>
      </div>
    </div>

      <p>&nbsp</p>
      <hr>

      <div class="row">
        <div class="col-md-12">
          <strong>HealthCare Files</strong>
          <br>
          <br>
          <% @prospect.attachments.where(service_type: 'healthcare').each do |attachment| %>  
            <div class="attachment">
              <div class="row">
                <div class="col-md-10">
                	<em><%= link_to "#{attachment.description}", attachment.document_url, target: :_blank %></em>
                	<p class="posted-by">Uploaded by <%= attachment.user.advisor_first_name + ' ' + attachment.user.advisor_last_name %> on
                	<%= attachment.created_at.strftime("%m/%d/%y") %></p>
            		</div>
            
                <div class="col-md-2">
            			<% if attachment.user_id == current_user.id %>
            				<%= link_to "Edit", edit_prospect_attachment_path(attachment.prospect, attachment), class: "btn btn-warning btn-xs" %> &nbsp; 
            				<%= link_to "Delete", prospect_attachment_path(attachment.prospect, attachment), method: :delete,
            						data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>
            			<% end %>
            		</div>
            	</div>
            </div>
          <% end %>
          <br>
          <%= render 'attachments/hcs_form' %>
        </div>
      </div>

      <p>&nbsp</p>
      <hr>

    <br>
    <div class="row">
      <div class="col-md-12">
        <strong>HealthCare Comments</strong>
        <br>
        <%= render @prospect.comments.where.not(hcs_content: nil) %>
        <br>
        <%= render 'comments/hcs_form' %>
      </div>
    </div>
      
    <% end %>

app/views/prospects/_pay_show.html.erb
    <% if @prospect.pay_prospect %>
      <p>&nbsp;</p>

      <div class="row">
        <div class="col-md-3">
          <h4><strong>Instant Pay</strong></h4>
        </div>
        <div class="col-md-5">
          <br>
          Status: <em><%= @prospect.pay_status %></em><br>
    		    <% if !@prospect.pay_next_action_date.nil? %>
	      			<% if @prospect.pay_next_action_date < Date.today %>
	      				<div class="alert-alert">
	      			<% else %>
	      				<div>
	      			<% end %>		
	      			Next Action: <em><%= @prospect.pay_next_action_date.strftime("%m/%d/%Y") %> - <%= @prospect.pay_next_action %></em>
	      			</div>
	      		<% end %>
        </div>
        <div class="col-md-2"><br>
          <% if !@prospect.pay_submitted_to_branch? %>
            <%= link_to "https://get.branchapp.com/bc-lead-registration", :target => "_blank", class: "btn btn-success btn-sm pull-right" do %><i class="glyphicon glyphicon-leaf"></i> Register Lead with Branch<% end %>
          <% end %>
        </div>
        <div class="col-md-2"><br>
          <%= link_to "Edit Instant Pay", pay_path(@prospect), class: "btn btn-warning btn-sm" %>      
        </div>        
      </div>

      <p>&nbsp;</p>
      
      <div class="row">
        <div class="col-md-4">
          Intro Pres Date: <% if !@prospect.pay_intro_presentation_date.nil? %>
    		  <em><%= @prospect.pay_intro_presentation_date.strftime("%m/%d/%y") %></em><% end %>
    		  <br>
    		  Intro Presented by: <em><%= @prospect.pay_intro_presenter %></em>  
        </div>
        <div class="col-md-4">
          SME Presentation Date: <% if !@prospect.pay_sme_presentation_date.nil? %>
    		  <em><%= @prospect.pay_sme_presentation_date.strftime("%m/%d/%y") %></em><% end %><br>
    		  Subject Matter Expert: <em><%= @prospect.pay_sme %></em><br>
    		  Lead Submitted to Branch? 
      		  <% if @prospect.pay_submitted_to_branch? %>
      		    <em><strong>Yes</strong></em>
      		  <% else %>
      		    <em><strong>No</strong></em>
            <% end %>
        </div>
        <div class="col-md-4">
          Agreement Date: <% if !@prospect.pay_agreement_date.nil? %>
    		  <em><%= @prospect.pay_agreement_date.strftime("%m/%d/%y") %></em><% end %><br>
      		Total Hourly Employees: <em><strong><%= @prospect.pay_hourly_employees %></strong></em>
      	</div>
      </div>

      <p>&nbsp;</p>
      <div class="row">
        <div class="col-md-12">
          Pay Notes: <em><%= @prospect.pay_notes %></em>
        </div>
      </div>

      <p>&nbsp</p>
      <hr>

      <div class="row">
        <div class="col-md-12">
          <strong>Same Day Pay Files</strong>
          <br>
          <br>
          <% @prospect.attachments.where(service_type: 'pay').each do |attachment| %>  
            <div class="attachment">
              <div class="row">
                <div class="col-md-10">
                	<em><%= link_to "#{attachment.description}", attachment.document_url, target: :_blank %></em>
                	<p class="posted-by">Uploaded by <%= attachment.user.advisor_first_name + ' ' + attachment.user.advisor_last_name %> on
                	<%= attachment.created_at.strftime("%m/%d/%y") %></p>
            		</div>
            
                <div class="col-md-2">
            			<% if attachment.user_id == current_user.id %>
            				<%= link_to "Edit", edit_prospect_attachment_path(attachment.prospect, attachment), class: "btn btn-warning btn-xs" %> &nbsp; 
            				<%= link_to "Delete", prospect_attachment_path(attachment.prospect, attachment), method: :delete,
            						data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>
            			<% end %>
            		</div>
            	</div>
            </div>
          <% end %>
          <%= render 'attachments/pay_form' %>
        </div>
      </div>

      <p>&nbsp</p>
      <hr>

      <br>
      <div class="row">
        <div class="col-md-12">
        <strong>Same Day Pay Comments</strong>
          <%= render @prospect.comments.where.not(pay_content: nil) %>
          <br>
          <%= render 'comments/pay_form' %>
        </div>
      </div>
      
    <% end %>

app/views/prospects/shipping_lead_status.html.erb
<div class="col-md-4 col-md-offset-4">
	<div class="panel panel-gray">
	  <div class="panel-heading">
	  	<h4>Editing: &nbsp; <%= @prospect.organization %></h4>
	  </div>
	  <div class="prospect-show">
  		<%= simple_form_for @prospect, url: shipping_lead_status_update_path, method: :post do |f| %>
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<%= f.input :shipping_lead_status, collection: true, required: true, collection: [
																									'Submitted',
																									'Pending Review',
																									'Approved',
																									'Declined',
																									'Inactive'
																									], label: "Lead Status" %></div>
			</div>
		</div>
		<div class="panel-footer center">
			<%= link_to "Back", shipstore_path, class: "btn btn-default" %>
      <%= f.button :submit, class:"btn btn-slate" %>
    <% end %>
  	</div>
	</div>
</div>

app/views/prospects/show.html.erb
<div class="col-md-8 col-md-offset-2">
  
	<div class="panel panel-gray">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-8">
        <p class="header-title"><%= @prospect.organization %></p>
      </div>
      
      <div class="col-md-4">
        <div class="btn-group pull-right">
          <button type="button" class="btn btn-slate">Add New Opportunity</button>
          <button type="button" class="btn btn-slate dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <% if !@prospect.hcs_prospect && !current_user.shipstore && !current_user.branch %>
            	<li><%= link_to "Add HealthCare Opportunity", hcsq_path(@prospect) %></li>      
            <% end %>
            <% if !@prospect.shipping_prospect && !current_user.entrust && !current_user.branch%>
            	<li><%= link_to "Add Shipping Opportunity", shipping_profile_path(@prospect) %></li>      
            <% end %>
            <% if !@prospect.pay_prospect && !current_user.shipstore && !current_user.entrust %>
            	<li><%= link_to "Add Instant Payments Opportunity", pay_path(@prospect) %></li>      
            <% end %>
            <% if !@prospect.vcp_prospect && !current_user.shipstore && !current_user.entrust && !current_user.branch %>
            	<li><%= link_to "Add Accounts Payable Opportunity", vcp_path(@prospect) %></li>      
            <% end %>
          </ul>
        </div>
      </div>
    
    </div>
    <div class="row">
      <div class="col-md-12"><p class="prospect-posted-by"><em>Prospect created on
        <%= @prospect.created_at.strftime("%m/%d/%Y") %>, last updated on
        <% if !@prospect.comments.last.nil? %>
          <% if @prospect.comments.last.updated_at > @prospect.updated_at %>
        	  <%= @prospect.comments.last.updated_at.strftime("%m/%d/%Y") %></em></p>
          <% else %>
        	  <%= @prospect.updated_at.strftime("%m/%d/%Y") %></em></p>
          <% end %>
        <% else %>
        	<%= @prospect.updated_at.strftime("%m/%d/%Y") %></em></p>
    		<% end %>
  		</div>
    </div>
  </div>
  <div class="prospect-show">
    <div class="row">
			<div class="col-md-4">
        Prospect: <Strong><%= @prospect.organization %></Strong>			  
			</div>
			<div class="col-md-4">
        Advisor: <%= @prospect.user.advisor_name %>		  
			</div>    			
    </div>
    <br>    
    <div class="row">
			<div class="col-md-4">Address: <em><%= @prospect.street_address %></em>
				<%if @prospect.address2.nil? %><em>, <%= @prospect.address2 %></em><% end %><br>
				City/State: <em><%= @prospect.city %>, <%= @prospect.state %> <%= @prospect.zip %></em><br>
				Website: <%if !@prospect.website.nil? %><em><%= link_to @prospect.website, "http://" + @prospect.website, target: "_blank" %></em><% end %>
			</div>
      <div class="col-md-4">
        Phone: <em><%= @prospect.phone %></em><br>
      	Employees: <em><%= @prospect.employees %></em><br>
      	Annual Revenue: <em><%= @prospect.annual_revenue %></em>      	
  	  </div>
  	</div>
    <br>
    <br>
    <div class="row">
      <div class="col-md-4">
        <strong>Contact 1</strong><br>
        Name: <em><%= @prospect.contact1_first_name %> <%= @prospect.contact1_last_name %></em><br>
        Title: <em><%= @prospect.contact1_title %></em><br>
        Phone: <em><%= @prospect.contact1_phone %></em><br>
        Mobile: <em><%= @prospect.contact1_mobile %></em><br>
        Email: <%if !@prospect.contact1_email.nil? %>
          <em><%= link_to @prospect.contact1_email, "mailto:" + @prospect.contact1_email %></em><% end %>
      </div>
      <div class="col-md-4">
        <strong>Contact 2</strong><br>
        Name: <em><%= @prospect.contact2_first_name %> <%= @prospect.contact2_last_name %></em><br>
        Title: <em><%= @prospect.contact2_title %></em><br>
        Phone: <em><%= @prospect.contact2_phone %></em><br>
        Mobile: <em><%= @prospect.contact2_mobile %></em><br>
        Email: <%if !@prospect.contact2_email.nil? %>
          <em><%= link_to @prospect.contact2_email, "mailto:" + @prospect.contact2_email %></em><% end %>
      </div>
      <div class="col-md-2">
		    <%= link_to "Edit & Update", edit_prospect_path(@prospect), class: "btn btn-warning btn-sm" %>
  	  </div>
  	</div>
  	<br>
  	<br>
    <div class="row">
      <div class="col-md-12">Prospect Notes: <em><%= @prospect.prospect_notes %></em></div>
    </div>
    <br>

    <p>&nbsp;</p>
    
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#home">Select Opportunity</a></li>
      <% if @prospect.hcs_prospect? && !current_user.shipstore && !current_user.branch %>
      	<li><a data-toggle="tab" href="#health">HealthCare</a></li>      
      <% end %>
      <% if @prospect.shipping_prospect? && !current_user.entrust && !current_user.branch %>
      	<li><a data-toggle="tab" href="#ship">Shipping</a></li>     
      <% end %>
      <% if @prospect.pay_prospect? && !current_user.shipstore && !current_user.entrust %>
        <li><a data-toggle="tab" href="#pay">Instant Pay</a></li>   
      <% end %>
      <% if @prospect.vcp_prospect? && !current_user.shipstore && !current_user.entrust && !current_user.branch %>
      <li><a data-toggle="tab" href="#ap">Accounts Payable</a></li>  
      <% end %>
    </ul>
    
    <div class="tab-content">
      <div id="health" class="tab-pane fade">
        <%= render 'prospects/hcs_show' %>
      </div>
      <div id="ship" class="tab-pane fade">
       	<%= render 'prospects/shipping_show' %> 
      </div>
      <div id="pay" class="tab-pane fade">
       	<%= render 'prospects/pay_show' %> 
      </div>
      <div id="ap" class="tab-pane fade">
       	<%= render 'prospects/vcp_show' %> 
      </div>
    </div>

	</div>
	
  <div class="panel-footer">
    <% if !current_user.shipstore && !current_user.entrust && !current_user.branch %>
  		<%= link_to "Back", prospects_path, class: "btn btn-beige btn-sm" %>
  		<%= link_to "Delete", prospect_path(@prospect), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
  	<% end %>	
  </div>	

</div>