config/routes.rb
Rails.application.routes.draw do

  get 'healthcare_savings', to: 'pages#healthcare-savings'
  get 'instant_pay', to: 'pages#instant-pay'  
  get 'home', to: 'pages#home'
  get 'docs', to: 'pages#docs'
  get 'marketing', to: 'pages#marketing'
  get 'references', to: 'pages#references'
  get 'articles', to: 'pages#articles'
  get 'training', to: 'pages#training'
  get 'answers', to: 'pages#answers'
  get 'email-sequences', to: 'pages#email-sequences'
  get 'cold-phone-script', to: 'pages#cold-phone-script'
  get 'invite-webinar', to: 'pages#invite-webinar'
  get 'steps-to-sale', to: 'pages#steps-to-sale'
  get 'training-vids', to: 'pages#training-vids'
  get 'lead-generation', to: 'pages#lead-generation'
  get 'lead-generation-faq', to: 'pages#lead-generation-faq'
  get 'intelatek', to: 'prospects#intelatek'
  get 'dashboard', to: 'prospects#dashboard'
  get :new_lead, to: 'prospects#new_lead', as: :new_lead
  post :new_lead, to: 'prospects#new_lead_create', as: :new_lead_create
  get 'lead/:id', to: 'prospects#lead', as: :lead
  post 'lead/:id', to: 'prospects#lead_update', as: :lead_update
  get 'hcsq/:id', to: 'prospects#hcsq', as: :hcsq
  post 'hcsq/:id', to: 'prospects#hcsq_update', as: :hcsq_update
  get 'hcs/:id', to: 'prospects#hcs', as: :hcs
  post 'hcs/:id', to: 'prospects#hcs_update', as: :hcs_update  
  get 'entrust', to: 'prospects#entrust'
  get 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status', as: :hcs_lead_status
  post 'hcs_lead_status/:id', to: 'prospects#hcs_lead_status_update', as: :hcs_lead_status_update
  get 'vcp/:id', to: 'prospects#vcp', as: :vcp
  post 'vcp/:id', to: 'prospects#vcp_update', as: :vcp_update
  get 'branch', to: 'prospects#branch'
  get 'pay/:id', to: 'prospects#pay', as: :pay
  post 'pay/:id', to: 'prospects#pay_update', as: :pay_update
  get 'shipping_profile/:id', to: 'prospects#shipping_profile', as: :shipping_profile
  post 'shipping_profile/:id', to: 'prospects#shipping_profile_update', as: :shipping_profile_update
  get 'shipping/:id', to: 'prospects#shipping', as: :shipping
  post 'shipping/:id', to: 'prospects#shipping_update', as: :shipping_update
  get 'shipstore', to: 'prospects#shipstore'
  get 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status', as: :shipping_lead_status
  post 'shipping_lead_status/:id', to: 'prospects#shipping_lead_status_update', as: :shipping_lead_status_update
  get 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status', as: :shipping_opportunity_status
  post 'shipping_opportunity_status/:id', to: 'prospects#shipping_opportunity_status_update', as: :shipping_opportunity_status_update  
  get :export_users, to: 'users#export_users', as: :export_users
  
  match '/users',     to: 'users#index',  via: 'get'
  
  # ************** I removed the line below to get Add User to work but not sure what effect it may have down the road ***********
  # match '/users/:id', to: 'users#show',   via: 'get'

  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'

  resources :users do
    resources :comments
    resources :attachments    
    collection { post :import }
  end

  resources :prospects do
    resources :comments
    resources :attachments    
    collection { post :import }
  end
    root 'pages#home'
  # root 'users#start_page'
end

app/views/layouts/_footer.html.erb
  <nav class="navbar navbar-fixed-bottom">
      <p align="center"><br>&copy; 2018 Application Developed by Chris Cunningham </p>
  </nav>

app/views/layouts/_head.html.erb
  <head>
    <title>Blue Coast CRM</title>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Chris Cunningham">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" %>    
    <%= csrf_meta_tags %>
  </head>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <% unless ((key.to_s == 'timedout') || value.blank?) %>
    <div class="alert alert-<%= key %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
          <li>
            <%= value %>
          </li>
        </ul>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-default navbar-fixed-top text-shadow">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to image_tag("bclogo.png", alt: "logo"), '/', class: 'navbar-brand' %>
            <!--<h3><strong>Blue Coast CRM</strong></h3>-->
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

    				<% if user_signed_in? %>

              <% if current_user.intelatek %>
    					  <li><%= link_to intelatek_path do %><i class="glyphicon glyphicon-knight"></i> IntelaTek<% end %></li>
              <% end %>      

              <li><%= link_to home_path do %><i class="fa fa-home"></i> Home<% end %></li>
              
              <% if current_user.manager %>
    					  <li><%= link_to dashboard_path do %><i class="glyphicon glyphicon-th"></i> Dashboard<% end %></li>
    					  <li><%= link_to users_path do %><i class="fa fa-users"></i> Users<% end %></li>
    					<% end %>
    					
              <% if current_user.staff %>    					  
                <li><%= link_to new_user_path, class: "nav-link" do %><i class="fa fa-user-plus"></i> Add User<% end %></li>    					  
              <% end %>

              <!--<li class="nav-item dropdown">-->
              <!--  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
              <!--    Services-->
              <!--  </a>-->
              <!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
              <!--    <ul class="nav">-->
              <!--    <li><#%= link_to healthcare_savings_path do %><i class="fa fa-user-md"></i> HealthCare<#% end %></li>-->
              <!--    <li><#%= link_to healthcare_savings_path do %><i class="glyphicon glyphicon-warning-sign"></i> Coming Soon<#% end %></li>-->
              <!--    <li><#%= link_to healthcare_savings_path do %><i class="glyphicon glyphicon-warning-sign"></i> Coming Soon<#% end %></li>                  -->
              <!--    </ul>-->
              <!--  </div>-->
              <!--</li>-->

              <li>
                <% if current_user.shipstore %>
                  <%= link_to shipstore_path, class: 'nav-link' do %><i class="fa fa-crosshairs"></i> Prospects<% end %>
                <% elsif current_user.entrust %>
                  <%= link_to entrust_path, class: 'nav-link' do %><i class="fa fa-crosshairs"></i> Prospects<% end %>              
                <% elsif current_user.branch %>
                  <%= link_to branch_path, class: 'nav-link' do %><i class="fa fa-crosshairs"></i> Prospects<% end %>
                <% elsif current_user.staff %>
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-crosshairs"></i> Prospects</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <ul class="nav">
                      <li><%= link_to prospects_path, class: 'nav-link' do %> All Prospects<% end %></li>
                      <li><%= link_to shipstore_path, class: 'nav-link' do %> Shipping<% end %></li>
                      <li><%= link_to entrust_path, class: 'nav-link' do %> HealthCare<% end %></li>
                      <li><%= link_to branch_path, class: 'nav-link' do %> Instant Pay<% end %></li>                  
                    </ul>
                  </div>                
                <% else %>
                  <%= link_to prospects_path, class: 'nav-link' do %><i class="fa fa-crosshairs"></i> Prospects<% end %>
                <% end %>
              </li>

              <%# if !current_user.shipstore && !current_user.entrust && !current_user.branch %>            
                <li><%= link_to new_prospect_path, class: "nav-link" do %><i class="fa fa-user-plus"></i> Add Prospect<% end %></li>
              <%# end %>
              
    					<li><%= link_to edit_user_registration_path do %><i class="fa fa-gear"></i> <%= current_user.advisor_name  %><% end %></li>

    					<li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-lock"></i> Sign out<% end %></li>

    				<% else %>

    					<!--<li><%#= link_to new_user_registration_path do %><i class="fa fa-user-plus"></i> Sign up<#% end %></li> -->

    					<!--<li><%#= link_to new_user_session_path do %><i class="fa fa-unlock"></i> Log in<%# end %></li>-->
    					
    				<% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!-- Author Chris Cunningham October 7th 2018 -->

<!DOCTYPE html>
<html lang="en">

	<%= render 'layouts/head' %>
  
  <body>

	  <%= render 'layouts/nav' %>

    <div class="container-fluid">

      <%= render 'layouts/messages' %>       

    	<%= yield %>
    </div>
 
	  <%#= render 'layouts/footer' %>
	  
  </body>
  
</html>